# 本地开发的配置文件参考模板
spring.datasource.dynamic.datasource.master.driver-class-name=org.postgresql.Driver
spring.datasource.dynamic.datasource.master.url=jdbc:postgresql://pgm-8vb5g50kv356g56r0o.pgsql.zhangbei.rds.aliyuncs.com:1921/liudayu_ks?currentSchema=yzx2&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&useInformationSchema=true
spring.datasource.dynamic.datasource.master.username=liudayu_ks
spring.datasource.dynamic.datasource.master.password=liudayu**ks**A0227
spring.datasource.dynamic.strict=true

mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl

spring.redis.host=39.101.174.9
spring.redis.port=31053
spring.redis.password=redis
spring.redis.database=8
spring.redis.timeout=10s

gago.bmp.access-key-id=4w1WIj6w8F461xR8Ru0d496f
gago.bmp.access-key-secret=89q9oND9LI0hy9529W164n49zyn5g5d8
gago.bmp.project-code=SDSDYSLJXGBZNTZHNYXM-00149
gago.bmp.region-name=从化
